[package]
name = "pirana-telemetry"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
pirana-core = { path = "../pirana-core" }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
metrics = { workspace = true }
metrics-exporter-prometheus = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
