use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Unique identifier for orders placed by the system
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct OrderId(pub Uuid);

impl OrderId {
    pub fn new() -> Self {
        Self(Uuid::new_v4())
    }
}

impl Default for OrderId {
    fn default() -> Self {
        Self::new()
    }
}

/// Unique identifier for signals generated by the AI layer
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct SignalId(pub Uuid);

impl SignalId {
    pub fn new() -> Self {
        Self(Uuid::new_v4())
    }
}

impl Default for SignalId {
    fn default() -> Self {
        Self::new()
    }
}

/// Trading pair representation
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct Symbol(pub String);

impl Symbol {
    pub fn new<S: Into<String>>(s: S) -> Self {
        Self(s.into().to_uppercase())
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl From<&str> for Symbol {
    fn from(s: &str) -> Self {
        Self::new(s)
    }
}

/// Side of an order
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Side {
    Buy,
    Sell,
}

/// Order type
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum OrderType {
    Market,
    Limit,
    StopLimit,
    StopMarket,
    /// Immediate or Cancel
    IOC,
    /// Fill or Kill
    FOK,
}

/// Order status on the exchange
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum OrderStatus {
    Pending,
    Open,
    PartiallyFilled,
    Filled,
    Cancelled,
    Rejected,
    Expired,
}

/// Time in force policies
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum TimeInForce {
    GoodTilCancelled,
    ImmediateOrCancel,
    FillOrKill,
}

/// A price level in the order book
#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub struct PriceLevel {
    pub price: f64,
    pub quantity: f64,
    pub order_count: u32,
}

/// A single market tick
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Tick {
    pub symbol: Symbol,
    pub price: f64,
    pub quantity: f64,
    pub side: Side,
    pub timestamp: DateTime<Utc>,
    pub trade_id: u64,
}

/// Order book snapshot
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderBookSnapshot {
    pub symbol: Symbol,
    pub bids: Vec<PriceLevel>,
    pub asks: Vec<PriceLevel>,
    pub timestamp: DateTime<Utc>,
    pub sequence: u64,
}

/// A trade executed on the exchange
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Trade {
    pub trade_id: u64,
    pub symbol: Symbol,
    pub price: f64,
    pub quantity: f64,
    pub side: Side,
    pub timestamp: DateTime<Utc>,
    pub is_maker: bool,
}

/// Signal generated by the AI layer
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Signal {
    pub id: SignalId,
    pub signal_type: SignalType,
    pub target_asset: Symbol,
    pub confidence_score: f64,
    pub market_regime: MarketRegime,
    pub rationale: String,
    pub recommended_params: SignalParams,
    pub timestamp: DateTime<Utc>,
    pub invalidation_level: f64,
}

/// Types of signals the AI layer can generate
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum SignalType {
    AccumulationEntry,
    DistributionExit,
    Hold,
    DefensiveHalt,
    SpreadCapture,
    MarketMaking,
}

/// Market regime classification
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum MarketRegime {
    LowVolatilityTrending,
    LowVolatilityRanging,
    HighVolatilityTrending,
    HighVolatilityRanging,
    HighVolatilityLiquidationEvent,
    LowLiquidity,
    StructuralInefficiency,
}

/// Parameters recommended by the AI layer for a signal
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SignalParams {
    pub entry_zone: (f64, f64),
    pub invalidation_level: f64,
    pub volatility_adjusted_tp: f64,
    pub position_size_pct: f64,
    pub max_slippage_bps: u32,
}

/// Risk assessment result
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RiskAssessment {
    pub approved: bool,
    pub rejection_reason: Option<String>,
    pub adjusted_position_size: f64,
    pub current_exposure_pct: f64,
    pub daily_drawdown_pct: f64,
    pub weekly_drawdown_pct: f64,
    pub consecutive_losses: u32,
}

/// System operational mode
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum SystemMode {
    /// Normal trading operations
    Active,
    /// Reduced exposure, conservative only
    Defensive,
    /// All trading halted, human review required
    Halted,
    /// System starting up
    Initializing,
    /// System shutting down
    ShuttingDown,
}

/// Balance information for an asset
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Balance {
    pub asset: String,
    pub free: f64,
    pub locked: f64,
}

/// Account state
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AccountState {
    pub balances: Vec<Balance>,
    pub total_btc_value: f64,
    pub timestamp: DateTime<Utc>,
}

/// Position in a market
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Position {
    pub symbol: Symbol,
    pub side: Side,
    pub quantity: f64,
    pub entry_price: f64,
    pub unrealized_pnl: f64,
    pub realized_pnl: f64,
    pub opened_at: DateTime<Utc>,
}
